language: node_js
node_js:
  - "0.12"
env:
  global:
    - secure: "OSzgC5cSAK7uEAvnMKx7uD7IHmWotVSxCeor3SuVL1OUlCln/anSc+hBgp6ZMSwCsMAuwfRnfCoV5yFQepR9D3KO5GvhGQiFrQqiupPfucBwgVJV7fLLyoqmyWuR7fyEPYFCaDF7iaqZAQhFFprRKD+WjYVgCDIS1KIEflgJNJaAE403e6qc3YqocVCsccsJfCSM5jVOAf6XvVwXH4Bg0vjzqvzrXdKwsIeEONFnE+4R/74ClKY3pKEZnJJLL5COI44zfoYmusAtFvkUd3TqTfQ9/oABfBT59SW8PzLcmHkJn20YqohPdRiYKc0DDRxIk/8TdXLPbCEpBP/0Yoju1WhbwSHF8Rs+ItmCn8Ip5heWBD0nJfSoIJ+QyM+ikZHDKHFpqTYwUt+Plkc3B8gRBOHUr3zFt1aUPv2gv8W/OXxcidBDxKja+AAH06Zxferof6RUeToEA/Bwq0sdZgwpUnlYj937mIRIbAYFA4X108BpUo1keQhlsy1+Z5AU9B9p8I/P/Qxj6zqpdClFMemyezf2x6l03LRcYLjv9Ph+aG2BQXcienMM1nakucHEdia68RND/xGtfQiGU23BkA8D2Y5SJtjdvUUBtwpWd1eKaPRZ1eBltvuwlNui98VTZDRSmtF0A6+mto7UjNx3OaPcoP4rUUG6015VLAuUJbYcnsI="
